import "./globals.css";
import { Inter } from "next/font/google";
import InnerLayout from "./Innerlayout";
import { Providers } from "./redux/provider";
import "react-toastify/dist/ReactToastify.css";
import Toast from "./components/Common/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
      </head> */}
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          <Toast />
          <InnerLayout>{children}</InnerLayout>
        </Providers>
      </body>
    </html>
  );
}
